# Generated by Django 5.2.4 on 2025-11-03 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador sem espaços – ex.: NOME', unique=True, verbose_name='Slug')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Serviço')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço (R$)')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do serviço', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Serviços inativos não aparecem no agendamento', verbose_name='Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='LihStudio.profissional')),
            ],
            options={
                'ordering': ['data', 'hora'],
                'unique_together': {('profissional', 'data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Pagamento')),
                ('pagamento_status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('processando', 'Processando')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('contabilizar', models.BooleanField(default=False, help_text='Marque se este agendamento deve ser incluído nos relatórios de faturamento.', verbose_name='Contabilizar no Faturamento')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor Total (R$)')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('servico_nome_snapshot', models.CharField(blank=True, help_text='Nome do serviço no momento do agendamento (não muda)', max_length=100, verbose_name='Nome do Serviço (Snapshot)')),
                ('servico_preco_snapshot', models.DecimalField(blank=True, decimal_places=2, help_text='Preço do serviço no momento do agendamento (não muda)', max_digits=8, null=True, verbose_name='Preço do Serviço (Snapshot)')),
                ('data', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='pendente', max_length=10, verbose_name='Status do Agendamento')),
                ('manutencao_lembrada', models.BooleanField(default=False, help_text='Marcar se o lembrete de manutenção foi enviado após 15 dias', verbose_name='Lembrete de manutenção enviado?')),
                ('confirmado', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hora_backup', models.TimeField(blank=True, null=True, verbose_name='Hora (backup)')),
                ('hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LihStudio.horariodisponivel')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='LihStudio.profissional')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='LihStudio.servico', verbose_name='Serviço')),
            ],
        ),
    ]
